import tkinter as tk
import matplotlib.pyplot as plt
from matplotlib_venn import venn3, venn3_circles
from matplotlib_venn import venn2

window = tk.Tk()
window.title('Venn Draw')
window.geometry('650x350')
var = tk.StringVar()

r2 = tk.Radiobutton(window, text='2', variable=var, value=2)
r3 = tk.Radiobutton(window, text='3', variable=var, value=3)
r2.grid(row=0,column=0)
r3.grid(row=0,column=5)

tk.Label(window, text='Name A').grid(row=1,column=0)
tk.Label(window, text='Name B').grid(row=2,column=0)
tk.Label(window, text='A').grid(row=4,column=0)
tk.Label(window, text='B').grid(row=5,column=0)
tk.Label(window, text='AB').grid(row=6,column=0)
e2nA = tk.Entry(window)
e2nA.grid(row=1, column=1)
e2nB = tk.Entry(window)
e2nB.grid(row=2, column=1)
e2A = tk.Entry(window)
e2A.grid(row=4, column=1)
e2B = tk.Entry(window)
e2B.grid(row=5, column=1)
e2AB = tk.Entry(window)
e2AB.grid(row=6, column=1)

tk.Label(window, text='Color A').grid(row=4,column=2)
tk.Label(window, text='Color B').grid(row=5,column=2)
tk.Label(window, text='Color AB').grid(row=6,column=2)
e2cA = tk.Entry(window)
e2cA.grid(row=4, column=3)
e2cB = tk.Entry(window)
e2cB.grid(row=5, column=3)
e2cAB = tk.Entry(window)
e2cAB.grid(row=6, column=3)

tk.Label(window, text='Name A').grid(row=1,column=5)
tk.Label(window, text='Name B').grid(row=2,column=5)
tk.Label(window, text='Name C').grid(row=3,column=5)
tk.Label(window, text='A').grid(row=4,column=5)
tk.Label(window, text='B').grid(row=5,column=5)
tk.Label(window, text='AB').grid(row=6,column=5)
tk.Label(window, text='C').grid(row=7,column=5)
tk.Label(window, text='AC').grid(row=8,column=5)
tk.Label(window, text='BC').grid(row=9,column=5)
tk.Label(window, text='ABC').grid(row=10,column=5)
e3nA = tk.Entry(window)
e3nA.grid(row=1, column=6)
e3nB = tk.Entry(window)
e3nB.grid(row=2, column=6)
e3nC = tk.Entry(window)
e3nC.grid(row=3, column=6)
e3A = tk.Entry(window)
e3A.grid(row=4, column=6)
e3B = tk.Entry(window)
e3B.grid(row=5, column=6)
e3AB = tk.Entry(window)
e3AB.grid(row=6, column=6)
e3C = tk.Entry(window)
e3C.grid(row=7, column=6)
e3AC = tk.Entry(window)
e3AC.grid(row=8, column=6)
e3BC = tk.Entry(window)
e3BC.grid(row=9, column=6)
e3ABC = tk.Entry(window)
e3ABC.grid(row=10, column=6)

def click_Enter():
    if var.get()=='2':
        plt.figure(figsize=(5,5))
        v = venn2(subsets = (int(e2A.get()),int(e2B.get()),int(e2AB.get())), set_labels = (e2nA.get(),e2nB.get()))
        v.get_patch_by_id('10').set_color(e2cA.get())
        v.get_patch_by_id('11').set_color(e2cAB.get())
        v.get_patch_by_id('01').set_color(e2cB.get())
        plt.savefig(efp.get()+'\\'+efn.get(), dpi=300)
        plt.show()
        
    if var.get()=='3':
        plt.figure(figsize=(5,5))
        v = venn3(subsets = (int(e3A.get()),int(e3B.get()),int(e3AB.get()),int(e3C.get()),int(e3AC.get()),int(e3BC.get()),int(e3ABC.get())), set_labels = (e3nA.get(),e3nB.get(),e3nC.get()))
        c = venn3_circles(subsets = (int(e3A.get()),int(e3B.get()),int(e3AB.get()),int(e3C.get()),int(e3AC.get()),int(e3BC.get()),int(e3ABC.get())), linewidth=1, color="black")
        plt.savefig(efp.get()+'\\'+efn.get(), dpi=300)
        plt.show()

tk.Label(window, text='Save Path:').grid(row=11,column=0)
efp = tk.Entry(window, width=45)
efp.grid(row=11, column=1, columnspan=3)
tk.Label(window, text='File Name:').grid(row=12,column=0)
efn = tk.Entry(window, width=45)
efn.grid(row=12, column=1, columnspan=3)
bEnter = tk.Button(window,text='Enter', command=click_Enter)
bEnter.grid(row=13,column=0)

window.mainloop()